name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/281554095545/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'github-actions@atomjuice-production.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - uses: actions/cache@v1
      id: cache
      with:
        path: .cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-test
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black setuptools wheel twine keyrings.google-artifactregistry-auth
        pip install -r requirements.txt
    - name: Run Black
      run: |
        black aj_micro_utils --check --exclude "/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|_build|buck-out|build|dist|migrations)/"
    - name: Build
      run: |
        export TAG_VERSION=${GITHUB_REF#refs/tags/}
        python3 setup.py bdist_wheel
    - name: Artifact
      run: twine upload --repository-url https://europe-python.pkg.dev/atomjuice-production/python/ dist/* --verbose
